# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_head.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet_head.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11packet_head.proto\x12\x05proto\"\xdd\x02\n\nPacketHead\x12\x11\n\tpacket_id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x0f\n\x07user_ip\x18\x03 \x01(\r\x12\x17\n\x0fuser_session_id\x18\x04 \x01(\r\x12\x13\n\x0b\x64ispatch_ip\x18\x05 \x01(\r\x12\x15\n\rgameserver_ip\x18\x06 \x01(\r\x12\x0e\n\x06rpc_id\x18\x07 \x01(\r\x12\x17\n\x0f\x65net_channel_id\x18\x08 \x01(\r\x12\x18\n\x10\x65net_is_reliable\x18\t \x01(\r\x12\x15\n\rnodeserver_ip\x18\n \x01(\r\x12\x11\n\trecv_time\x18\x0b \x01(\r\x12\x19\n\x11rpc_begin_time_ms\x18\x0c \x01(\r\x12\x16\n\x0etarget_service\x18\r \x01(\r\x12\x11\n\tdbgate_ip\x18\x0e \x01(\r\x12\x10\n\x08\x63ustom_1\x18\x0f \x01(\r\x12\x10\n\x08\x63ustom_2\x18\x10 \x01(\r\"\xd4\x01\n\x0b\x44\x65\x62ugNotify\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12+\n\x07retcode\x18\x03 \x01(\x0e\x32\x1a.proto.DebugNotify.Retcode\"_\n\x04\x45num\x12\x08\n\x04ZERO\x10\x00\x12\n\n\x06\x43MD_ID\x10\x65\x12\x12\n\x0eTARGET_SERVICE\x10\x65\x12\x13\n\x0f\x45NET_CHANNEL_ID\x10\x02\x12\x14\n\x10\x45NET_IS_RELIABLE\x10\x01\x1a\x02\x10\x01\"\x1d\n\x07Retcode\x12\x08\n\x04SUCC\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x62\x06proto3')
)



_DEBUGNOTIFY_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='proto.DebugNotify.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_ID', index=1, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TARGET_SERVICE', index=2, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENET_CHANNEL_ID', index=3, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENET_IS_RELIABLE', index=4, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001')),
  serialized_start=467,
  serialized_end=562,
)
_sym_db.RegisterEnumDescriptor(_DEBUGNOTIFY_ENUM)

_DEBUGNOTIFY_RETCODE = _descriptor.EnumDescriptor(
  name='Retcode',
  full_name='proto.DebugNotify.Retcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=564,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_DEBUGNOTIFY_RETCODE)


_PACKETHEAD = _descriptor.Descriptor(
  name='PacketHead',
  full_name='proto.PacketHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_id', full_name='proto.PacketHead.packet_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='proto.PacketHead.user_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_ip', full_name='proto.PacketHead.user_ip', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_session_id', full_name='proto.PacketHead.user_session_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dispatch_ip', full_name='proto.PacketHead.dispatch_ip', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameserver_ip', full_name='proto.PacketHead.gameserver_ip', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='proto.PacketHead.rpc_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enet_channel_id', full_name='proto.PacketHead.enet_channel_id', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enet_is_reliable', full_name='proto.PacketHead.enet_is_reliable', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeserver_ip', full_name='proto.PacketHead.nodeserver_ip', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recv_time', full_name='proto.PacketHead.recv_time', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpc_begin_time_ms', full_name='proto.PacketHead.rpc_begin_time_ms', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_service', full_name='proto.PacketHead.target_service', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dbgate_ip', full_name='proto.PacketHead.dbgate_ip', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_1', full_name='proto.PacketHead.custom_1', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_2', full_name='proto.PacketHead.custom_2', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=378,
)


_DEBUGNOTIFY = _descriptor.Descriptor(
  name='DebugNotify',
  full_name='proto.DebugNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.DebugNotify.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.DebugNotify.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retcode', full_name='proto.DebugNotify.retcode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEBUGNOTIFY_ENUM,
    _DEBUGNOTIFY_RETCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=593,
)

_DEBUGNOTIFY.fields_by_name['retcode'].enum_type = _DEBUGNOTIFY_RETCODE
_DEBUGNOTIFY_ENUM.containing_type = _DEBUGNOTIFY
_DEBUGNOTIFY_RETCODE.containing_type = _DEBUGNOTIFY
DESCRIPTOR.message_types_by_name['PacketHead'] = _PACKETHEAD
DESCRIPTOR.message_types_by_name['DebugNotify'] = _DEBUGNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketHead = _reflection.GeneratedProtocolMessageType('PacketHead', (_message.Message,), dict(
  DESCRIPTOR = _PACKETHEAD,
  __module__ = 'packet_head_pb2'
  # @@protoc_insertion_point(class_scope:proto.PacketHead)
  ))
_sym_db.RegisterMessage(PacketHead)

DebugNotify = _reflection.GeneratedProtocolMessageType('DebugNotify', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGNOTIFY,
  __module__ = 'packet_head_pb2'
  # @@protoc_insertion_point(class_scope:proto.DebugNotify)
  ))
_sym_db.RegisterMessage(DebugNotify)


_DEBUGNOTIFY_ENUM.has_options = True
_DEBUGNOTIFY_ENUM._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
