// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_shop.proto

#ifndef PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class BuyGoodsReq;
class BuyGoodsReqDefaultTypeInternal;
extern BuyGoodsReqDefaultTypeInternal _BuyGoodsReq_default_instance_;
class BuyGoodsRsp;
class BuyGoodsRspDefaultTypeInternal;
extern BuyGoodsRspDefaultTypeInternal _BuyGoodsRsp_default_instance_;
class GetShopReq;
class GetShopReqDefaultTypeInternal;
extern GetShopReqDefaultTypeInternal _GetShopReq_default_instance_;
class GetShopRsp;
class GetShopRspDefaultTypeInternal;
extern GetShopRspDefaultTypeInternal _GetShopRsp_default_instance_;
class Shop;
class ShopDefaultTypeInternal;
extern ShopDefaultTypeInternal _Shop_default_instance_;
class ShopGoods;
class ShopGoodsDefaultTypeInternal;
extern ShopGoodsDefaultTypeInternal _ShopGoods_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fshop_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fshop_2eproto

enum GetShopReq_CmdId {
  GetShopReq_CmdId_NONE = 0,
  GetShopReq_CmdId_CMD_ID = 701,
  GetShopReq_CmdId_ENET_CHANNEL_ID = 0,
  GetShopReq_CmdId_ENET_IS_RELIABLE = 1,
  GetShopReq_CmdId_IS_ALLOW_CLIENT = 1,
  GetShopReq_CmdId_GetShopReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopReq_CmdId_GetShopReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopReq_CmdId_IsValid(int value);
const GetShopReq_CmdId GetShopReq_CmdId_CmdId_MIN = GetShopReq_CmdId_NONE;
const GetShopReq_CmdId GetShopReq_CmdId_CmdId_MAX = GetShopReq_CmdId_CMD_ID;
const int GetShopReq_CmdId_CmdId_ARRAYSIZE = GetShopReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopReq_CmdId_descriptor();
inline const ::std::string& GetShopReq_CmdId_Name(GetShopReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopReq_CmdId_descriptor(), value);
}
inline bool GetShopReq_CmdId_Parse(
    const ::std::string& name, GetShopReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopReq_CmdId>(
    GetShopReq_CmdId_descriptor(), name, value);
}
enum GetShopRsp_CmdId {
  GetShopRsp_CmdId_NONE = 0,
  GetShopRsp_CmdId_CMD_ID = 702,
  GetShopRsp_CmdId_ENET_CHANNEL_ID = 0,
  GetShopRsp_CmdId_ENET_IS_RELIABLE = 1,
  GetShopRsp_CmdId_GetShopRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopRsp_CmdId_GetShopRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopRsp_CmdId_IsValid(int value);
const GetShopRsp_CmdId GetShopRsp_CmdId_CmdId_MIN = GetShopRsp_CmdId_NONE;
const GetShopRsp_CmdId GetShopRsp_CmdId_CmdId_MAX = GetShopRsp_CmdId_CMD_ID;
const int GetShopRsp_CmdId_CmdId_ARRAYSIZE = GetShopRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopRsp_CmdId_descriptor();
inline const ::std::string& GetShopRsp_CmdId_Name(GetShopRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopRsp_CmdId_descriptor(), value);
}
inline bool GetShopRsp_CmdId_Parse(
    const ::std::string& name, GetShopRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopRsp_CmdId>(
    GetShopRsp_CmdId_descriptor(), name, value);
}
enum BuyGoodsReq_CmdId {
  BuyGoodsReq_CmdId_NONE = 0,
  BuyGoodsReq_CmdId_CMD_ID = 703,
  BuyGoodsReq_CmdId_ENET_CHANNEL_ID = 0,
  BuyGoodsReq_CmdId_ENET_IS_RELIABLE = 1,
  BuyGoodsReq_CmdId_IS_ALLOW_CLIENT = 1,
  BuyGoodsReq_CmdId_BuyGoodsReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BuyGoodsReq_CmdId_BuyGoodsReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BuyGoodsReq_CmdId_IsValid(int value);
const BuyGoodsReq_CmdId BuyGoodsReq_CmdId_CmdId_MIN = BuyGoodsReq_CmdId_NONE;
const BuyGoodsReq_CmdId BuyGoodsReq_CmdId_CmdId_MAX = BuyGoodsReq_CmdId_CMD_ID;
const int BuyGoodsReq_CmdId_CmdId_ARRAYSIZE = BuyGoodsReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BuyGoodsReq_CmdId_descriptor();
inline const ::std::string& BuyGoodsReq_CmdId_Name(BuyGoodsReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BuyGoodsReq_CmdId_descriptor(), value);
}
inline bool BuyGoodsReq_CmdId_Parse(
    const ::std::string& name, BuyGoodsReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuyGoodsReq_CmdId>(
    BuyGoodsReq_CmdId_descriptor(), name, value);
}
enum BuyGoodsRsp_CmdId {
  BuyGoodsRsp_CmdId_NONE = 0,
  BuyGoodsRsp_CmdId_CMD_ID = 704,
  BuyGoodsRsp_CmdId_ENET_CHANNEL_ID = 0,
  BuyGoodsRsp_CmdId_ENET_IS_RELIABLE = 1,
  BuyGoodsRsp_CmdId_BuyGoodsRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BuyGoodsRsp_CmdId_BuyGoodsRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BuyGoodsRsp_CmdId_IsValid(int value);
const BuyGoodsRsp_CmdId BuyGoodsRsp_CmdId_CmdId_MIN = BuyGoodsRsp_CmdId_NONE;
const BuyGoodsRsp_CmdId BuyGoodsRsp_CmdId_CmdId_MAX = BuyGoodsRsp_CmdId_CMD_ID;
const int BuyGoodsRsp_CmdId_CmdId_ARRAYSIZE = BuyGoodsRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BuyGoodsRsp_CmdId_descriptor();
inline const ::std::string& BuyGoodsRsp_CmdId_Name(BuyGoodsRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BuyGoodsRsp_CmdId_descriptor(), value);
}
inline bool BuyGoodsRsp_CmdId_Parse(
    const ::std::string& name, BuyGoodsRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuyGoodsRsp_CmdId>(
    BuyGoodsRsp_CmdId_descriptor(), name, value);
}
// ===================================================================

class ShopGoods : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.ShopGoods) */ {
 public:
  ShopGoods();
  virtual ~ShopGoods();

  ShopGoods(const ShopGoods& from);

  inline ShopGoods& operator=(const ShopGoods& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShopGoods(ShopGoods&& from) noexcept
    : ShopGoods() {
    *this = ::std::move(from);
  }

  inline ShopGoods& operator=(ShopGoods&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ShopGoods& default_instance();

  static inline const ShopGoods* internal_default_instance() {
    return reinterpret_cast<const ShopGoods*>(
               &_ShopGoods_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ShopGoods* other);
  friend void swap(ShopGoods& a, ShopGoods& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShopGoods* New() const PROTOBUF_FINAL { return New(NULL); }

  ShopGoods* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ShopGoods& from);
  void MergeFrom(const ShopGoods& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ShopGoods* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.ItemParam cost_item_list = 5;
  int cost_item_list_size() const;
  void clear_cost_item_list();
  static const int kCostItemListFieldNumber = 5;
  const ::proto::ItemParam& cost_item_list(int index) const;
  ::proto::ItemParam* mutable_cost_item_list(int index);
  ::proto::ItemParam* add_cost_item_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
      mutable_cost_item_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
      cost_item_list() const;

  // repeated uint32 pre_goods_id_list = 13;
  int pre_goods_id_list_size() const;
  void clear_pre_goods_id_list();
  static const int kPreGoodsIdListFieldNumber = 13;
  ::google::protobuf::uint32 pre_goods_id_list(int index) const;
  void set_pre_goods_id_list(int index, ::google::protobuf::uint32 value);
  void add_pre_goods_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pre_goods_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pre_goods_id_list();

  // .proto.ItemParam goods_item = 2;
  bool has_goods_item() const;
  void clear_goods_item();
  static const int kGoodsItemFieldNumber = 2;
  const ::proto::ItemParam& goods_item() const;
  ::proto::ItemParam* mutable_goods_item();
  ::proto::ItemParam* release_goods_item();
  void set_allocated_goods_item(::proto::ItemParam* goods_item);

  // uint32 goods_id = 1;
  void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  ::google::protobuf::uint32 goods_id() const;
  void set_goods_id(::google::protobuf::uint32 value);

  // uint32 scoin = 3;
  void clear_scoin();
  static const int kScoinFieldNumber = 3;
  ::google::protobuf::uint32 scoin() const;
  void set_scoin(::google::protobuf::uint32 value);

  // uint32 hcoin = 4;
  void clear_hcoin();
  static const int kHcoinFieldNumber = 4;
  ::google::protobuf::uint32 hcoin() const;
  void set_hcoin(::google::protobuf::uint32 value);

  // uint32 bought_num = 6;
  void clear_bought_num();
  static const int kBoughtNumFieldNumber = 6;
  ::google::protobuf::uint32 bought_num() const;
  void set_bought_num(::google::protobuf::uint32 value);

  // uint32 buy_limit = 7;
  void clear_buy_limit();
  static const int kBuyLimitFieldNumber = 7;
  ::google::protobuf::uint32 buy_limit() const;
  void set_buy_limit(::google::protobuf::uint32 value);

  // uint32 begin_time = 8;
  void clear_begin_time();
  static const int kBeginTimeFieldNumber = 8;
  ::google::protobuf::uint32 begin_time() const;
  void set_begin_time(::google::protobuf::uint32 value);

  // uint32 end_time = 9;
  void clear_end_time();
  static const int kEndTimeFieldNumber = 9;
  ::google::protobuf::uint32 end_time() const;
  void set_end_time(::google::protobuf::uint32 value);

  // uint32 next_refresh_time = 10;
  void clear_next_refresh_time();
  static const int kNextRefreshTimeFieldNumber = 10;
  ::google::protobuf::uint32 next_refresh_time() const;
  void set_next_refresh_time(::google::protobuf::uint32 value);

  // uint32 min_level = 11;
  void clear_min_level();
  static const int kMinLevelFieldNumber = 11;
  ::google::protobuf::uint32 min_level() const;
  void set_min_level(::google::protobuf::uint32 value);

  // uint32 max_level = 12;
  void clear_max_level();
  static const int kMaxLevelFieldNumber = 12;
  ::google::protobuf::uint32 max_level() const;
  void set_max_level(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.ShopGoods)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam > cost_item_list_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pre_goods_id_list_;
  mutable int _pre_goods_id_list_cached_byte_size_;
  ::proto::ItemParam* goods_item_;
  ::google::protobuf::uint32 goods_id_;
  ::google::protobuf::uint32 scoin_;
  ::google::protobuf::uint32 hcoin_;
  ::google::protobuf::uint32 bought_num_;
  ::google::protobuf::uint32 buy_limit_;
  ::google::protobuf::uint32 begin_time_;
  ::google::protobuf::uint32 end_time_;
  ::google::protobuf::uint32 next_refresh_time_;
  ::google::protobuf::uint32 min_level_;
  ::google::protobuf::uint32 max_level_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Shop : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Shop) */ {
 public:
  Shop();
  virtual ~Shop();

  Shop(const Shop& from);

  inline Shop& operator=(const Shop& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Shop(Shop&& from) noexcept
    : Shop() {
    *this = ::std::move(from);
  }

  inline Shop& operator=(Shop&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Shop& default_instance();

  static inline const Shop* internal_default_instance() {
    return reinterpret_cast<const Shop*>(
               &_Shop_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Shop* other);
  friend void swap(Shop& a, Shop& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Shop* New() const PROTOBUF_FINAL { return New(NULL); }

  Shop* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Shop& from);
  void MergeFrom(const Shop& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Shop* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.ShopGoods goods_list = 2;
  int goods_list_size() const;
  void clear_goods_list();
  static const int kGoodsListFieldNumber = 2;
  const ::proto::ShopGoods& goods_list(int index) const;
  ::proto::ShopGoods* mutable_goods_list(int index);
  ::proto::ShopGoods* add_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >*
      mutable_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >&
      goods_list() const;

  // uint32 shop_type = 1;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 1;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.Shop)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods > goods_list_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopReq) */ {
 public:
  GetShopReq();
  virtual ~GetShopReq();

  GetShopReq(const GetShopReq& from);

  inline GetShopReq& operator=(const GetShopReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopReq(GetShopReq&& from) noexcept
    : GetShopReq() {
    *this = ::std::move(from);
  }

  inline GetShopReq& operator=(GetShopReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopReq& default_instance();

  static inline const GetShopReq* internal_default_instance() {
    return reinterpret_cast<const GetShopReq*>(
               &_GetShopReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetShopReq* other);
  friend void swap(GetShopReq& a, GetShopReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopReq& from);
  void MergeFrom(const GetShopReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopReq_CmdId CmdId;
  static const CmdId NONE =
    GetShopReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GetShopReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GetShopReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 shop_type = 1;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 1;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GetShopReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopRsp) */ {
 public:
  GetShopRsp();
  virtual ~GetShopRsp();

  GetShopRsp(const GetShopRsp& from);

  inline GetShopRsp& operator=(const GetShopRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopRsp(GetShopRsp&& from) noexcept
    : GetShopRsp() {
    *this = ::std::move(from);
  }

  inline GetShopRsp& operator=(GetShopRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopRsp& default_instance();

  static inline const GetShopRsp* internal_default_instance() {
    return reinterpret_cast<const GetShopRsp*>(
               &_GetShopRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GetShopRsp* other);
  friend void swap(GetShopRsp& a, GetShopRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopRsp& from);
  void MergeFrom(const GetShopRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopRsp_CmdId CmdId;
  static const CmdId NONE =
    GetShopRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GetShopRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.Shop shop = 2;
  bool has_shop() const;
  void clear_shop();
  static const int kShopFieldNumber = 2;
  const ::proto::Shop& shop() const;
  ::proto::Shop* mutable_shop();
  ::proto::Shop* release_shop();
  void set_allocated_shop(::proto::Shop* shop);

  // int32 retcode = 1;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 1;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GetShopRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::Shop* shop_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BuyGoodsReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BuyGoodsReq) */ {
 public:
  BuyGoodsReq();
  virtual ~BuyGoodsReq();

  BuyGoodsReq(const BuyGoodsReq& from);

  inline BuyGoodsReq& operator=(const BuyGoodsReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuyGoodsReq(BuyGoodsReq&& from) noexcept
    : BuyGoodsReq() {
    *this = ::std::move(from);
  }

  inline BuyGoodsReq& operator=(BuyGoodsReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuyGoodsReq& default_instance();

  static inline const BuyGoodsReq* internal_default_instance() {
    return reinterpret_cast<const BuyGoodsReq*>(
               &_BuyGoodsReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(BuyGoodsReq* other);
  friend void swap(BuyGoodsReq& a, BuyGoodsReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuyGoodsReq* New() const PROTOBUF_FINAL { return New(NULL); }

  BuyGoodsReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BuyGoodsReq& from);
  void MergeFrom(const BuyGoodsReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BuyGoodsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BuyGoodsReq_CmdId CmdId;
  static const CmdId NONE =
    BuyGoodsReq_CmdId_NONE;
  static const CmdId CMD_ID =
    BuyGoodsReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BuyGoodsReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BuyGoodsReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    BuyGoodsReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return BuyGoodsReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BuyGoodsReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BuyGoodsReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BuyGoodsReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BuyGoodsReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BuyGoodsReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BuyGoodsReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.ShopGoods goods = 2;
  bool has_goods() const;
  void clear_goods();
  static const int kGoodsFieldNumber = 2;
  const ::proto::ShopGoods& goods() const;
  ::proto::ShopGoods* mutable_goods();
  ::proto::ShopGoods* release_goods();
  void set_allocated_goods(::proto::ShopGoods* goods);

  // uint32 shop_type = 1;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 1;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // uint32 buy_count = 3;
  void clear_buy_count();
  static const int kBuyCountFieldNumber = 3;
  ::google::protobuf::uint32 buy_count() const;
  void set_buy_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BuyGoodsReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::ShopGoods* goods_;
  ::google::protobuf::uint32 shop_type_;
  ::google::protobuf::uint32 buy_count_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BuyGoodsRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BuyGoodsRsp) */ {
 public:
  BuyGoodsRsp();
  virtual ~BuyGoodsRsp();

  BuyGoodsRsp(const BuyGoodsRsp& from);

  inline BuyGoodsRsp& operator=(const BuyGoodsRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuyGoodsRsp(BuyGoodsRsp&& from) noexcept
    : BuyGoodsRsp() {
    *this = ::std::move(from);
  }

  inline BuyGoodsRsp& operator=(BuyGoodsRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuyGoodsRsp& default_instance();

  static inline const BuyGoodsRsp* internal_default_instance() {
    return reinterpret_cast<const BuyGoodsRsp*>(
               &_BuyGoodsRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(BuyGoodsRsp* other);
  friend void swap(BuyGoodsRsp& a, BuyGoodsRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuyGoodsRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  BuyGoodsRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BuyGoodsRsp& from);
  void MergeFrom(const BuyGoodsRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BuyGoodsRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BuyGoodsRsp_CmdId CmdId;
  static const CmdId NONE =
    BuyGoodsRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    BuyGoodsRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BuyGoodsRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BuyGoodsRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return BuyGoodsRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BuyGoodsRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BuyGoodsRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BuyGoodsRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BuyGoodsRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BuyGoodsRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BuyGoodsRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.ShopGoods goods = 3;
  bool has_goods() const;
  void clear_goods();
  static const int kGoodsFieldNumber = 3;
  const ::proto::ShopGoods& goods() const;
  ::proto::ShopGoods* mutable_goods();
  ::proto::ShopGoods* release_goods();
  void set_allocated_goods(::proto::ShopGoods* goods);

  // int32 retcode = 1;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 1;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // uint32 shop_type = 2;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 2;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // uint32 buy_count = 4;
  void clear_buy_count();
  static const int kBuyCountFieldNumber = 4;
  ::google::protobuf::uint32 buy_count() const;
  void set_buy_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BuyGoodsRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::ShopGoods* goods_;
  ::google::protobuf::int32 retcode_;
  ::google::protobuf::uint32 shop_type_;
  ::google::protobuf::uint32 buy_count_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ShopGoods

// uint32 goods_id = 1;
inline void ShopGoods::clear_goods_id() {
  goods_id_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::goods_id() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.goods_id)
  return goods_id_;
}
inline void ShopGoods::set_goods_id(::google::protobuf::uint32 value) {
  
  goods_id_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.goods_id)
}

// .proto.ItemParam goods_item = 2;
inline bool ShopGoods::has_goods_item() const {
  return this != internal_default_instance() && goods_item_ != NULL;
}
inline void ShopGoods::clear_goods_item() {
  if (GetArenaNoVirtual() == NULL && goods_item_ != NULL) delete goods_item_;
  goods_item_ = NULL;
}
inline const ::proto::ItemParam& ShopGoods::goods_item() const {
  const ::proto::ItemParam* p = goods_item_;
  // @@protoc_insertion_point(field_get:proto.ShopGoods.goods_item)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::ItemParam*>(
      &::proto::_ItemParam_default_instance_);
}
inline ::proto::ItemParam* ShopGoods::mutable_goods_item() {
  
  if (goods_item_ == NULL) {
    goods_item_ = new ::proto::ItemParam;
  }
  // @@protoc_insertion_point(field_mutable:proto.ShopGoods.goods_item)
  return goods_item_;
}
inline ::proto::ItemParam* ShopGoods::release_goods_item() {
  // @@protoc_insertion_point(field_release:proto.ShopGoods.goods_item)
  
  ::proto::ItemParam* temp = goods_item_;
  goods_item_ = NULL;
  return temp;
}
inline void ShopGoods::set_allocated_goods_item(::proto::ItemParam* goods_item) {
  delete goods_item_;
  goods_item_ = goods_item;
  if (goods_item) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ShopGoods.goods_item)
}

// uint32 scoin = 3;
inline void ShopGoods::clear_scoin() {
  scoin_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::scoin() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.scoin)
  return scoin_;
}
inline void ShopGoods::set_scoin(::google::protobuf::uint32 value) {
  
  scoin_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.scoin)
}

// uint32 hcoin = 4;
inline void ShopGoods::clear_hcoin() {
  hcoin_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::hcoin() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.hcoin)
  return hcoin_;
}
inline void ShopGoods::set_hcoin(::google::protobuf::uint32 value) {
  
  hcoin_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.hcoin)
}

// repeated .proto.ItemParam cost_item_list = 5;
inline int ShopGoods::cost_item_list_size() const {
  return cost_item_list_.size();
}
inline void ShopGoods::clear_cost_item_list() {
  cost_item_list_.Clear();
}
inline const ::proto::ItemParam& ShopGoods::cost_item_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.cost_item_list)
  return cost_item_list_.Get(index);
}
inline ::proto::ItemParam* ShopGoods::mutable_cost_item_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.ShopGoods.cost_item_list)
  return cost_item_list_.Mutable(index);
}
inline ::proto::ItemParam* ShopGoods::add_cost_item_list() {
  // @@protoc_insertion_point(field_add:proto.ShopGoods.cost_item_list)
  return cost_item_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
ShopGoods::mutable_cost_item_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ShopGoods.cost_item_list)
  return &cost_item_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
ShopGoods::cost_item_list() const {
  // @@protoc_insertion_point(field_list:proto.ShopGoods.cost_item_list)
  return cost_item_list_;
}

// uint32 bought_num = 6;
inline void ShopGoods::clear_bought_num() {
  bought_num_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::bought_num() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.bought_num)
  return bought_num_;
}
inline void ShopGoods::set_bought_num(::google::protobuf::uint32 value) {
  
  bought_num_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.bought_num)
}

// uint32 buy_limit = 7;
inline void ShopGoods::clear_buy_limit() {
  buy_limit_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::buy_limit() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.buy_limit)
  return buy_limit_;
}
inline void ShopGoods::set_buy_limit(::google::protobuf::uint32 value) {
  
  buy_limit_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.buy_limit)
}

// uint32 begin_time = 8;
inline void ShopGoods::clear_begin_time() {
  begin_time_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::begin_time() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.begin_time)
  return begin_time_;
}
inline void ShopGoods::set_begin_time(::google::protobuf::uint32 value) {
  
  begin_time_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.begin_time)
}

// uint32 end_time = 9;
inline void ShopGoods::clear_end_time() {
  end_time_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::end_time() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.end_time)
  return end_time_;
}
inline void ShopGoods::set_end_time(::google::protobuf::uint32 value) {
  
  end_time_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.end_time)
}

// uint32 next_refresh_time = 10;
inline void ShopGoods::clear_next_refresh_time() {
  next_refresh_time_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::next_refresh_time() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.next_refresh_time)
  return next_refresh_time_;
}
inline void ShopGoods::set_next_refresh_time(::google::protobuf::uint32 value) {
  
  next_refresh_time_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.next_refresh_time)
}

// uint32 min_level = 11;
inline void ShopGoods::clear_min_level() {
  min_level_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::min_level() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.min_level)
  return min_level_;
}
inline void ShopGoods::set_min_level(::google::protobuf::uint32 value) {
  
  min_level_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.min_level)
}

// uint32 max_level = 12;
inline void ShopGoods::clear_max_level() {
  max_level_ = 0u;
}
inline ::google::protobuf::uint32 ShopGoods::max_level() const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.max_level)
  return max_level_;
}
inline void ShopGoods::set_max_level(::google::protobuf::uint32 value) {
  
  max_level_ = value;
  // @@protoc_insertion_point(field_set:proto.ShopGoods.max_level)
}

// repeated uint32 pre_goods_id_list = 13;
inline int ShopGoods::pre_goods_id_list_size() const {
  return pre_goods_id_list_.size();
}
inline void ShopGoods::clear_pre_goods_id_list() {
  pre_goods_id_list_.Clear();
}
inline ::google::protobuf::uint32 ShopGoods::pre_goods_id_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ShopGoods.pre_goods_id_list)
  return pre_goods_id_list_.Get(index);
}
inline void ShopGoods::set_pre_goods_id_list(int index, ::google::protobuf::uint32 value) {
  pre_goods_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.ShopGoods.pre_goods_id_list)
}
inline void ShopGoods::add_pre_goods_id_list(::google::protobuf::uint32 value) {
  pre_goods_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.ShopGoods.pre_goods_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ShopGoods::pre_goods_id_list() const {
  // @@protoc_insertion_point(field_list:proto.ShopGoods.pre_goods_id_list)
  return pre_goods_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ShopGoods::mutable_pre_goods_id_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ShopGoods.pre_goods_id_list)
  return &pre_goods_id_list_;
}

// -------------------------------------------------------------------

// Shop

// uint32 shop_type = 1;
inline void Shop::clear_shop_type() {
  shop_type_ = 0u;
}
inline ::google::protobuf::uint32 Shop::shop_type() const {
  // @@protoc_insertion_point(field_get:proto.Shop.shop_type)
  return shop_type_;
}
inline void Shop::set_shop_type(::google::protobuf::uint32 value) {
  
  shop_type_ = value;
  // @@protoc_insertion_point(field_set:proto.Shop.shop_type)
}

// repeated .proto.ShopGoods goods_list = 2;
inline int Shop::goods_list_size() const {
  return goods_list_.size();
}
inline void Shop::clear_goods_list() {
  goods_list_.Clear();
}
inline const ::proto::ShopGoods& Shop::goods_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.Shop.goods_list)
  return goods_list_.Get(index);
}
inline ::proto::ShopGoods* Shop::mutable_goods_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.Shop.goods_list)
  return goods_list_.Mutable(index);
}
inline ::proto::ShopGoods* Shop::add_goods_list() {
  // @@protoc_insertion_point(field_add:proto.Shop.goods_list)
  return goods_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >*
Shop::mutable_goods_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.Shop.goods_list)
  return &goods_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >&
Shop::goods_list() const {
  // @@protoc_insertion_point(field_list:proto.Shop.goods_list)
  return goods_list_;
}

// -------------------------------------------------------------------

// GetShopReq

// uint32 shop_type = 1;
inline void GetShopReq::clear_shop_type() {
  shop_type_ = 0u;
}
inline ::google::protobuf::uint32 GetShopReq::shop_type() const {
  // @@protoc_insertion_point(field_get:proto.GetShopReq.shop_type)
  return shop_type_;
}
inline void GetShopReq::set_shop_type(::google::protobuf::uint32 value) {
  
  shop_type_ = value;
  // @@protoc_insertion_point(field_set:proto.GetShopReq.shop_type)
}

// -------------------------------------------------------------------

// GetShopRsp

// int32 retcode = 1;
inline void GetShopRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 GetShopRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.GetShopRsp.retcode)
  return retcode_;
}
inline void GetShopRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.GetShopRsp.retcode)
}

// .proto.Shop shop = 2;
inline bool GetShopRsp::has_shop() const {
  return this != internal_default_instance() && shop_ != NULL;
}
inline void GetShopRsp::clear_shop() {
  if (GetArenaNoVirtual() == NULL && shop_ != NULL) delete shop_;
  shop_ = NULL;
}
inline const ::proto::Shop& GetShopRsp::shop() const {
  const ::proto::Shop* p = shop_;
  // @@protoc_insertion_point(field_get:proto.GetShopRsp.shop)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Shop*>(
      &::proto::_Shop_default_instance_);
}
inline ::proto::Shop* GetShopRsp::mutable_shop() {
  
  if (shop_ == NULL) {
    shop_ = new ::proto::Shop;
  }
  // @@protoc_insertion_point(field_mutable:proto.GetShopRsp.shop)
  return shop_;
}
inline ::proto::Shop* GetShopRsp::release_shop() {
  // @@protoc_insertion_point(field_release:proto.GetShopRsp.shop)
  
  ::proto::Shop* temp = shop_;
  shop_ = NULL;
  return temp;
}
inline void GetShopRsp::set_allocated_shop(::proto::Shop* shop) {
  delete shop_;
  shop_ = shop;
  if (shop) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.GetShopRsp.shop)
}

// -------------------------------------------------------------------

// BuyGoodsReq

// uint32 shop_type = 1;
inline void BuyGoodsReq::clear_shop_type() {
  shop_type_ = 0u;
}
inline ::google::protobuf::uint32 BuyGoodsReq::shop_type() const {
  // @@protoc_insertion_point(field_get:proto.BuyGoodsReq.shop_type)
  return shop_type_;
}
inline void BuyGoodsReq::set_shop_type(::google::protobuf::uint32 value) {
  
  shop_type_ = value;
  // @@protoc_insertion_point(field_set:proto.BuyGoodsReq.shop_type)
}

// .proto.ShopGoods goods = 2;
inline bool BuyGoodsReq::has_goods() const {
  return this != internal_default_instance() && goods_ != NULL;
}
inline void BuyGoodsReq::clear_goods() {
  if (GetArenaNoVirtual() == NULL && goods_ != NULL) delete goods_;
  goods_ = NULL;
}
inline const ::proto::ShopGoods& BuyGoodsReq::goods() const {
  const ::proto::ShopGoods* p = goods_;
  // @@protoc_insertion_point(field_get:proto.BuyGoodsReq.goods)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::ShopGoods*>(
      &::proto::_ShopGoods_default_instance_);
}
inline ::proto::ShopGoods* BuyGoodsReq::mutable_goods() {
  
  if (goods_ == NULL) {
    goods_ = new ::proto::ShopGoods;
  }
  // @@protoc_insertion_point(field_mutable:proto.BuyGoodsReq.goods)
  return goods_;
}
inline ::proto::ShopGoods* BuyGoodsReq::release_goods() {
  // @@protoc_insertion_point(field_release:proto.BuyGoodsReq.goods)
  
  ::proto::ShopGoods* temp = goods_;
  goods_ = NULL;
  return temp;
}
inline void BuyGoodsReq::set_allocated_goods(::proto::ShopGoods* goods) {
  delete goods_;
  goods_ = goods;
  if (goods) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.BuyGoodsReq.goods)
}

// uint32 buy_count = 3;
inline void BuyGoodsReq::clear_buy_count() {
  buy_count_ = 0u;
}
inline ::google::protobuf::uint32 BuyGoodsReq::buy_count() const {
  // @@protoc_insertion_point(field_get:proto.BuyGoodsReq.buy_count)
  return buy_count_;
}
inline void BuyGoodsReq::set_buy_count(::google::protobuf::uint32 value) {
  
  buy_count_ = value;
  // @@protoc_insertion_point(field_set:proto.BuyGoodsReq.buy_count)
}

// -------------------------------------------------------------------

// BuyGoodsRsp

// int32 retcode = 1;
inline void BuyGoodsRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 BuyGoodsRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.BuyGoodsRsp.retcode)
  return retcode_;
}
inline void BuyGoodsRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.BuyGoodsRsp.retcode)
}

// uint32 shop_type = 2;
inline void BuyGoodsRsp::clear_shop_type() {
  shop_type_ = 0u;
}
inline ::google::protobuf::uint32 BuyGoodsRsp::shop_type() const {
  // @@protoc_insertion_point(field_get:proto.BuyGoodsRsp.shop_type)
  return shop_type_;
}
inline void BuyGoodsRsp::set_shop_type(::google::protobuf::uint32 value) {
  
  shop_type_ = value;
  // @@protoc_insertion_point(field_set:proto.BuyGoodsRsp.shop_type)
}

// .proto.ShopGoods goods = 3;
inline bool BuyGoodsRsp::has_goods() const {
  return this != internal_default_instance() && goods_ != NULL;
}
inline void BuyGoodsRsp::clear_goods() {
  if (GetArenaNoVirtual() == NULL && goods_ != NULL) delete goods_;
  goods_ = NULL;
}
inline const ::proto::ShopGoods& BuyGoodsRsp::goods() const {
  const ::proto::ShopGoods* p = goods_;
  // @@protoc_insertion_point(field_get:proto.BuyGoodsRsp.goods)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::ShopGoods*>(
      &::proto::_ShopGoods_default_instance_);
}
inline ::proto::ShopGoods* BuyGoodsRsp::mutable_goods() {
  
  if (goods_ == NULL) {
    goods_ = new ::proto::ShopGoods;
  }
  // @@protoc_insertion_point(field_mutable:proto.BuyGoodsRsp.goods)
  return goods_;
}
inline ::proto::ShopGoods* BuyGoodsRsp::release_goods() {
  // @@protoc_insertion_point(field_release:proto.BuyGoodsRsp.goods)
  
  ::proto::ShopGoods* temp = goods_;
  goods_ = NULL;
  return temp;
}
inline void BuyGoodsRsp::set_allocated_goods(::proto::ShopGoods* goods) {
  delete goods_;
  goods_ = goods;
  if (goods) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.BuyGoodsRsp.goods)
}

// uint32 buy_count = 4;
inline void BuyGoodsRsp::clear_buy_count() {
  buy_count_ = 0u;
}
inline ::google::protobuf::uint32 BuyGoodsRsp::buy_count() const {
  // @@protoc_insertion_point(field_get:proto.BuyGoodsRsp.buy_count)
  return buy_count_;
}
inline void BuyGoodsRsp::set_buy_count(::google::protobuf::uint32 value) {
  
  buy_count_ = value;
  // @@protoc_insertion_point(field_set:proto.BuyGoodsRsp.buy_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::GetShopReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopReq_CmdId>() {
  return ::proto::GetShopReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetShopRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopRsp_CmdId>() {
  return ::proto::GetShopRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BuyGoodsReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BuyGoodsReq_CmdId>() {
  return ::proto::BuyGoodsReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BuyGoodsRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BuyGoodsRsp_CmdId>() {
  return ::proto::BuyGoodsRsp_CmdId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED
