# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd/cmd_monster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd/cmd_monster.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x63md/cmd_monster.proto\x12\x05proto\"\x80\x02\n\x16MonsterSummonTagNotify\x12\x19\n\x11monster_entity_id\x18\x01 \x01(\r\x12G\n\x0esummon_tag_map\x18\x02 \x03(\x0b\x32/.proto.MonsterSummonTagNotify.SummonTagMapEntry\x1a\x33\n\x11SummonTagMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"M\n\x05\x43mdId\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x06\x43MD_ID\x10\x95\n\x12\x13\n\x0f\x45NET_CHANNEL_ID\x10\x00\x12\x14\n\x10\x45NET_IS_RELIABLE\x10\x01\x1a\x02\x10\x01\x62\x06proto3')
)



_MONSTERSUMMONTAGNOTIFY_CMDID = _descriptor.EnumDescriptor(
  name='CmdId',
  full_name='proto.MonsterSummonTagNotify.CmdId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_ID', index=1, number=1301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENET_CHANNEL_ID', index=2, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENET_IS_RELIABLE', index=3, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001')),
  serialized_start=212,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_MONSTERSUMMONTAGNOTIFY_CMDID)


_MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY = _descriptor.Descriptor(
  name='SummonTagMapEntry',
  full_name='proto.MonsterSummonTagNotify.SummonTagMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.MonsterSummonTagNotify.SummonTagMapEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.MonsterSummonTagNotify.SummonTagMapEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=210,
)

_MONSTERSUMMONTAGNOTIFY = _descriptor.Descriptor(
  name='MonsterSummonTagNotify',
  full_name='proto.MonsterSummonTagNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster_entity_id', full_name='proto.MonsterSummonTagNotify.monster_entity_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summon_tag_map', full_name='proto.MonsterSummonTagNotify.summon_tag_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY, ],
  enum_types=[
    _MONSTERSUMMONTAGNOTIFY_CMDID,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=289,
)

_MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY.containing_type = _MONSTERSUMMONTAGNOTIFY
_MONSTERSUMMONTAGNOTIFY.fields_by_name['summon_tag_map'].message_type = _MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY
_MONSTERSUMMONTAGNOTIFY_CMDID.containing_type = _MONSTERSUMMONTAGNOTIFY
DESCRIPTOR.message_types_by_name['MonsterSummonTagNotify'] = _MONSTERSUMMONTAGNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonsterSummonTagNotify = _reflection.GeneratedProtocolMessageType('MonsterSummonTagNotify', (_message.Message,), dict(

  SummonTagMapEntry = _reflection.GeneratedProtocolMessageType('SummonTagMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY,
    __module__ = 'cmd.cmd_monster_pb2'
    # @@protoc_insertion_point(class_scope:proto.MonsterSummonTagNotify.SummonTagMapEntry)
    ))
  ,
  DESCRIPTOR = _MONSTERSUMMONTAGNOTIFY,
  __module__ = 'cmd.cmd_monster_pb2'
  # @@protoc_insertion_point(class_scope:proto.MonsterSummonTagNotify)
  ))
_sym_db.RegisterMessage(MonsterSummonTagNotify)
_sym_db.RegisterMessage(MonsterSummonTagNotify.SummonTagMapEntry)


_MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY.has_options = True
_MONSTERSUMMONTAGNOTIFY_SUMMONTAGMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_MONSTERSUMMONTAGNOTIFY_CMDID.has_options = True
_MONSTERSUMMONTAGNOTIFY_CMDID._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
