// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log/client/client_action_type.proto

#ifndef PROTOBUF_log_2fclient_2fclient_5faction_5ftype_2eproto__INCLUDED
#define PROTOBUF_log_2fclient_2fclient_5faction_5ftype_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
namespace proto_log {
}  // namespace proto_log

namespace proto_log {

namespace protobuf_log_2fclient_2fclient_5faction_5ftype_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_log_2fclient_2fclient_5faction_5ftype_2eproto

enum ClientActionType {
  CLIENT_ACTION_NONE = 0,
  CLIENT_ACTION_LOGIN = 1,
  CLIENT_ACTION_PING = 2,
  ClientActionType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ClientActionType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ClientActionType_IsValid(int value);
const ClientActionType ClientActionType_MIN = CLIENT_ACTION_NONE;
const ClientActionType ClientActionType_MAX = CLIENT_ACTION_PING;
const int ClientActionType_ARRAYSIZE = ClientActionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ClientActionType_descriptor();
inline const ::std::string& ClientActionType_Name(ClientActionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ClientActionType_descriptor(), value);
}
inline bool ClientActionType_Parse(
    const ::std::string& name, ClientActionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ClientActionType>(
    ClientActionType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto_log

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto_log::ClientActionType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto_log::ClientActionType>() {
  return ::proto_log::ClientActionType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_log_2fclient_2fclient_5faction_5ftype_2eproto__INCLUDED
